### ISSUE TITLE
Python3 support for SMA Inverters is not working

### ISSUE THREAD

**Issue by k-quigley** [openenergymonitor/emonhub#102]
When enabling the support for BT connections to SMA inverters the emonhub process fails.
This is a bit of a "catch-all" issue for things we've observed; whilst checking the latest code with our SB-5000TL

There are a number of issues which include:
- If the Bluetooth python modules are missing, there is nothing which informs the user
- Exception in string types handling the inverter pin code/password
- Bluetooth message handling is broken. (both sending and receiving packets are not working under python3)
- A regression issue which broke receiving large BT packets, was introduced in the following commit: https://github.com/openenergymonitor/emonhub/commit/035d266645471a93e66b13a23d80f73873d22db7 

- During long term debugging we find that the Bluetooth processes on the Rpi sometimes stops responding.

**Comment by TrystanLea** [comment]
Thanks for fixing @k-quigley
