### ISSUE TITLE
Move HTTP send into HTTP Interfacer

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonhub#155]
The HTTP send data is not inside the HTTP Interfacer. I am sure this is a historical mistake but it should be rectified.

![image](https://user-images.githubusercontent.com/1322749/115146001-94d6dd00-a04c-11eb-9602-421b83f55473.png)

This may relate to issue #125

**Comment by TrystanLea** [comment]
Thanks @borpin this is now fixed
