### ISSUE TITLE
ModbusTCP Interfacer

### ISSUE THREAD

**Issue by gjonesy84** [openenergymonitor/emonhub#166]
Modbustcp interfacer stopped working this morning both in emonhub and node red (running on emonhun- pi3b).

Any suggestions why the emonhub would stop working at a drop of a hat. 

Other devices still on network and fully functional.

**Comment by gjonesy84** [comment]
Yes. Can t remember what it was I did to fix it. Sorry

**Comment by borpin** [comment]
Could you close the issue, please?
