### ISSUE TITLE
SDM630

### ISSUE THREAD

**Issue by njordan77** [openenergymonitor/emonhub#168]
Hi,
is there a way to configure SDM630 smartmeter for all 3 phases.
I tried but it only shows a single phase....so i guess its not fully supported (??)

Thanks for any advice.
Norbert

**Comment by glynhudson** [comment]
Three-phase registers from SDM630 are now supported.

EI is energy imported 
EE is energy exported 
IN is current in the neutral 

https://docs.openenergymonitor.org/emonhub/emonhub-interfacers.html#sdm630-three-phase

![Screenshot from 2023-07-21 13-16-34](https://github.com/openenergymonitor/emonhub/assets/758844/9b1fb580-69de-42ae-9345-0f44e50517fc)
