### ISSUE TITLE
High CPU load caused by frequent check of settings in emonhub

### ISSUE THREAD

**Issue by Trickx** [openenergymonitor/emonhub#17]
self._setup.run() within emonhub.py is causing high CP load

Is there a need to check for updated settings with this frequency?
Implementation issue?

https://community.openenergymonitor.org/t/high-cpu-consumption-caused-by-checking-settings-in-emonhub/2230

**Comment by glynhudson** [comment]
Fixed by https://github.com/openenergymonitor/emonhub/pull/22
