### ISSUE TITLE
Incorrect escape sequence during install (for non-pi users)

### ISSUE THREAD

**Issue by stuartpittaway** [openenergymonitor/emonhub#202]
See the thread in...
https://community.openenergymonitor.org/t/emonhub-will-not-start-on-ubuntu-install/24381/18

Which relates to this line...
https://github.com/openenergymonitor/emonhub/blob/0627fe7f4cbeda4fe3124718d53427aee48317a0/install.sh#L141C5-L141C87

**Comment by borpin** [comment]
@stuartpittaway I think this can be closed.
