### ISSUE TITLE
Did you mean to delete these readmes?

### ISSUE THREAD

**Issue by R1CH-T** [openenergymonitor/emonhub#23]
https://github.com/openenergymonitor/emonhub/commit/8cedfe0ae056b59849ece8fd062924091e56b9ff#diff-3754706ebfa54512a8d8c164628ab70c

**Comment by glynhudson** [comment]
No, I just meant to rename them to `readme.md` so they could be easily read on github.com. I've now restored and renamed them. Thanks ! :+1:
