### ISSUE TITLE
Modbus interfacer imlementation

### ISSUE THREAD

**Issue by pb66** [openenergymonitor/emonhub#43]
I just happened to be looking at the recent changes to the modbus readme and noticed the settings.

https://github.com/openenergymonitor/emonhub/blob/dea95f70cffe0f2cb9eab4f70d1b364496ea7613/conf/interfacer_examples/modbus/modbusTCP.emonhub.conf#L39

https://github.com/openenergymonitor/emonhub/blob/dea95f70cffe0f2cb9eab4f70d1b364496ea7613/conf/interfacer_examples/modbus/modbusTCP.emonhub.conf#L41

https://github.com/openenergymonitor/emonhub/blob/dea95f70cffe0f2cb9eab4f70d1b364496ea7613/conf/interfacer_examples/modbus/modbusTCP.emonhub.conf#L233

This is essentially the same information in triplicate, that is 3 times the user needs to input the data and 3 times it could be erroneous.

Same for the naming

https://github.com/openenergymonitor/emonhub/blob/dea95f70cffe0f2cb9eab4f70d1b364496ea7613/conf/interfacer_examples/modbus/modbusTCP.emonhub.conf#L35

https://github.com/openenergymonitor/emonhub/blob/dea95f70cffe0f2cb9eab4f70d1b364496ea7613/conf/interfacer_examples/modbus/modbusTCP.emonhub.conf#L232

**Comment by alexandrecuer** [comment]
Hello

I totally agree with the duplications in the conf file....

Moreover this modbusTCP code implements only the read_holding_registers function and not the read_input_registers one....if you want to use the read_input_registers function, you have to change it in the EmonModbusTcpInterfacer.py file

Anyway it is working perfectly...I found it very useful in EmonCMS
I have two different modbusTCP equipments (sofrelS500 and HMSanybusAB7007) and emonhub interacts perfectly with them....I don't know if a lot of people do use modbus equipments among the EmonCMS users but I hope this functionnality will remain

The only problem I found is that you have to monitor more than one register address...with only one address, I have a sort of bug (the thread is closing and restaring with no success) which disappears with two or more addresses

best regards

Alex
