### ISSUE TITLE
socket interfacer "timestamped" setting not working as expected

### ISSUE THREAD

**Issue by pb66** [openenergymonitor/emonhub#47]
see https://community.openenergymonitor.org/t/new-node-data-not-showing-in-emoncms-org/6402/21?u=pb66

All values True,true,False,false result in a True and force the user to provide a timestamp only removing the setting so the default kicks in will allow non-timestamped data.

**Comment by TrystanLea** [comment]
Fixed thanks @pb66 

https://github.com/openenergymonitor/emonhub/commit/3ce75707a8e4391cbc0fbff567e17667afa6439a
and
https://github.com/openenergymonitor/emonhub/commit/d7b17d5739cb134afe4eefb556eae8bae3985ae6
