### ISSUE TITLE
Dead link: EmonHub config file -> Nodes

### ISSUE THREAD

**Issue by Deathlesss** [openenergymonitor/emonhub#48]
The link in EmonHub config file under Node is 404:

```
[nodes]

## See config user guide: http://github.com/openenergymonitor/emonhub/blob/master/configuration.md

```

I assume it has to go to: https://github.com/openenergymonitor/emonhub/blob/emon-pi/configuration.md

??

**Comment by Deathlesss** [comment]
HM... on second thoughts, I guess the configuration does NOT update when an new version comes. So I have to manually update this text from [here](https://github.com/openenergymonitor/emonhub/blob/emon-pi/conf/emonpi.default.emonhub.conf) right?

https://github.com/openenergymonitor/emonhub/blob/emon-pi/conf/emonpi.default.emonhub.conf

**Comment by glynhudson** [comment]
Thanks, Fixed 👍

**Comment by Deathlesss** [comment]
thanks for fixing!
