### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by SlyRemarks** [openenergymonitor/emonhub#69]
```
10.### emonHub configuration file, for info see documentation:
11.### https://github.com/openenergymonitor/emonhub/blob/emon-pi/conf/emonhub.conf
...
85.## See config user guide: https://github.com/openenergymonitor/emonhub/blob/emon-pi/conf/emonhub.conf

```
These links should point here:
https://github.com/openenergymonitor/emonhub/blob/emon-pi/configuration.md

[courtesy of forum user Dave Howorth (https://community.openenergymonitor.org/t/typo-in-emonhub-conf/9410); likely a mistake in commit 56a65ee]

**Comment by glynhudson** [comment]
Done. I did some testing and realised updating emonhub.conf wil only update the default version not the version with user changes. It will mean users will not automatically get this fix. But at least its fixed on the master copy.
