### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonhub#78]
https://github.com/openenergymonitor/emonhub/blob/cb9da3c14babf8d7f0c2203450465b6e9111c99b/install.sh#L19

If I wanted to install just the emonhub onto a raw Raspbian, to take serial data and send it to emoncms, would this do it?

Are there assumptions re the Python Environment (2.7 or 3.x) that pip is installed, that git is installed?

Just asking for a friend 😄 

Can the script be named `install-emonbub.sh`?

**Comment by beaylott** [comment]
It maybe an idea to move to a virtual environment which can be setup from a requirements.txt file distributed with the repository. This is fairly standard practice these days for Python. 

And I maybe wrong but I think emonhub is on 2.7 still.

**Comment by borpin** [comment]
Yes is the short answer.
